### ISSUE TITLE
Some remote port will cause Invalid argument

### ISSUE THREAD

**Issue by ethan42411** [tttonyyy/ais-dispatcher#2]
When I set udp-dest for stream AIS data via UDP to MarineTraffic, will appear error like: `OSError: [Errno 22] Invalid argument`

Full Traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "dispatcher.py", line 96, in udpDispatcher
    [s.sendto(data, host) for host in destinations]
  File "dispatcher.py", line 96, in <listcomp>
    [s.sendto(data, host) for host in destinations]
OSError: [Errno 22] Invalid argument
```

I try to fix this problem. #3

**Comment by tttonyyy** [comment]
Thank you!  I will just test that here :)
